### ISSUE TITLE
Oops, add brackets to the 'ck' indexes

### ISSUE THREAD

**Issue by NomenConservandum** [aragami3070/PhysicLabsTerm3#1]
https://github.com/aragami3070/PhysicLabsTerm3/blob/beff5501025dce88e18fc5929635b08cb61de7dc/Laba15/sections/section%201.tex#L73

**Comment by aragami3070** [comment]
Хуй с ним, нам не до этого

**Comment by aragami3070** [comment]
Да, надо было закрыть, как не сделанную. Я случайно на автомате так закрыл.
